import pyautogui
import time

time.sleep(10)

while True:
	pyautogui.typewrite('Vendor Name: Vohra Wound Physicians of CA')
	time.sleep(3)
	pyautogui.press('enter')
	pyautogui.typewrite('Vendor TIN: 450924683')
	time.sleep(3)
	pyautogui.press('enter')
	pyautogui.typewrite('Effective Date: 01/01/2026')
	time.sleep(3)
	pyautogui.press('enter')
	pyautogui.typewrite('Contract Type: Specialty')
	time.sleep(3)
	pyautogui.press('enter')
	pyautogui.typewrite('IPA: BACP (Sacramento)')
	time.sleep(3)
	pyautogui.press('enter')
	pyautogui.press('enter')
	time.sleep(10)

	pyautogui.typewrite('Vendor Name: Tina Bhutani-Jacques MD, Inc. dba Synergy Dermatology')
	time.sleep(3)
	pyautogui.press('enter')
	pyautogui.typewrite('Vendor TIN: 990804986')
	time.sleep(3)
	pyautogui.press('enter')
	pyautogui.typewrite('Effective Date: 01/01/2026')
	time.sleep(3)
	pyautogui.press('enter')
	pyautogui.typewrite('Contract Type: Specialty')
	time.sleep(3)
	pyautogui.press('enter')
	pyautogui.typewrite('IPA: JADE')
	time.sleep(3)
	pyautogui.press('enter')
	pyautogui.press('enter')
	time.sleep(10)